---
title: ""
format:
  html:
    page-layout: custom
    css: styles_index.css
---

::: {.container-fluid}
::: {.content-wrapper}
::: {.text-content .custom-text-container}

#### Baillie-Gifford Pandemic Science Hub

<br />

Institute for Regeneration & Repair

5 Little France Drive

Edinburgh

EH16 4UU

United Kingdom

<i class="bi bi-telephone"></i> +44 (0)131 651 9514

```{r}
#| echo: false
library(leaflet)
leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lat=55.92081, lng=-3.130734726982889, popup="Baillie Gifford Pandemic Science Hub")
```

<br />

<br />

#### Queen Elizabeth University Hospital, Glasgow

<br />

Department of Critical Care

Queen Elizabeth University Hospital

1345 Govan Rd

Glasgow

G51 4TF

<i class="bi bi-telephone"></i> +44 (0)141 201 1100

```{r}
#| echo: false
library(leaflet)
leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lat=55.86222, lng=-4.34111, popup="QEUH")
```

:::
:::
:::

<br />

<br />