project:
  type: website

website:
  title: ""
  site-url: https://jemillar.io
  description: "The genomics of ARDS"
  twitter-card:
    creator: "@jemillarni"
  favicon: images/favicon.png

  navbar:
    logo: images/favicon.png
    background: primary
    align: left

    left:
      - text: ""
        href: docs/home/index.qmd
      - icon: stickies
        text: "Projects"
        href: docs/projects/projectlist.qmd
      - icon: book
        text: "Publications"
        href: docs/papers/publist.qmd
      - icon: terminal
        text: "Software/Data"
        href: docs/software/softlist.qmd
      - icon: person-rolodex
        text: "Contact"
        href: docs/contact/contact.qmd

    right:
      - icon: file-earmark-person
        text: "CV"
        href: cv.pdf
      - icon: github
        href: https://github.com/JonathanEMillar
      - icon: twitter
        href: https://twitter.com/jemillarni
      - icon: envelope
        href: mailto:jonathan.millar@ed.ac.uk

  page-footer:
    left: "© Copyright 2022 Jonathan Millar. Licensed CC-BY-NC 4.0."
    right:
      - icon: code
        href: https://github.com/JonathanEMillar/personal_website

format:
  html:
    theme:
      light: [materia]
      dark: [darkly]
    css: styles.css

filters:
  - shinylive
