project:
  type: website

website:
  title: ""
  site-url: https://jemillar.io
  description: ""
  twitter-card:
    creator: "@jemillarni"
  favicon: images/favicon.png
  search: false

  navbar:
    background: primary
    align: left

    left:
      - text: "**JOHNNY MILLAR**"
        href: docs/home/index.qmd
      - icon: person
        text: "About me"
        href: docs/about/index.qmd
      - icon: stickies
        text: "Projects"
        href: docs/projects/projectlist.qmd
      - icon: book
        text: "Publications"
        href: docs/papers/publist.qmd
      - icon: terminal
        text: "Software/Data"
        menu:
          - text: "R"
            href: docs/software/softlist.qmd
          - text: "Python"
            href: docs/software/python.qmd
          - text: "Web"
            href: docs/software/web.qmd
      - icon: file-earmark-person
        text: "CV"
        href: cv.pdf
      - icon: map
        text: "Contact"
        href: docs/contact/contact.qmd

  page-footer:
    left: "© Copyright 2022 Jonathan Millar. Licensed CC-BY-NC 4.0."
    right:
      - icon: code
        href: https://github.com/JonathanEMillar/personal_website

format:
  html:
    theme:
      light: [materia]
    css: styles.css

filters:
  - shinylive
