---
title: ""
format:
  html:
    page-layout: custom
    css: styles_index.css
    include-after-body:
      - text: |
          <script src="publications_eds.js"></script>
---
<script src="https://kit.fontawesome.com/caafde3ada.js" crossorigin="anonymous"></script>
<style>
/* Existing styles */
.year-ribbon {
    display: flex;
    flex-wrap: wrap;
    justify-content: left;
    gap: 10px;
    margin-top: 20px;
    margin-bottom: 20px;
    width: 200%;
}
.year-button {
    padding: 5px 10px;
    background-color: white;
    color: #17252a;
    border: none;
    cursor: pointer;
    transition: background-color 0.3s;
}
.year-button:hover, .year-button.active {
    background-color: white;
    color: #3aafa9;
}
.publications-list {
    margin-top: 20px;
}
.publication-item {
    margin-bottom: 15px;
    display: none;
    border-bottom: 1px solid #eee;
    padding-bottom: 15px;
}
.publication-item.active {
    display: block;
}
.publication-item a {
    color: #3aafa9;
    text-decoration: none;
    transition: color 0.3s ease;
}
.publication-item a:hover {
    text-decoration: none;
}

.accompany a {
    color: #3aafa9; /* Change this to your desired color */
    text-decoration: none;
    transition: color 0.3s ease;
}

.accompany a:hover {
    color: #2b7a78; /* Change this to your desired hover color */
    text-decoration: none;
}

</style>

:::{.container-fluid}
:::{.content-wrapper}
:::{.text-content .custom-text-container}

::: {.social-buttons}
<a href="https://orcid.org/0000-0002-4853-9377" class="btn-social" aria-label="ORCID"><i class="fab fa-orcid"></i></a>
<a href="https://scholar.google.com/citations?user=I8I6g0IAAAAJ&hl=en" class="btn-social" aria-label="Google Scholar"><i class="fas fa-graduation-cap"></i></a>
:::

::: {.title}

## Editorials

:::

<div class="year-ribbon">
<!-- Year buttons will be dynamically added here -->
</div>

<div class="publications-list">
<!-- Publication items will be dynamically added here -->
</div>

::: {.accompany}

### [Original articles](publist.qmd)

:::

::: {.accompany}

### [Letters](letters.qmd)

:::

::: {.accompany}

### [Book chapters](books.qmd)

:::

:::
:::
:::

<script>
document.addEventListener('DOMContentLoaded', function() {
    var acc = document.getElementsByClassName("accordion-header");
    for (var i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.maxHeight) {
                panel.style.maxHeight = null;
                panel.classList.remove("active");
            } else {
                panel.style.maxHeight = panel.scrollHeight + "px";
                panel.classList.add("active");
            }
        });
    }
});
</script>
