---
title: ""
page-layout: full
toc: true
toc-title: Publications
toc-depth: 4
toc-expand: true
toc-location: left
comments: false
editor: visual
---

### Original articles

------------------------------------------------------------------------

[Google Scholar](https://scholar.google.com/citations?user=I8I6g0IAAAAJ&hl=en&oi=ao)

[ORCID](https://orcid.org/0000-0002-4853-9377)

#### **2024**

------------------------------------------------------------------------

**Millar JE**, Clohisey-Hendry S, McMannus M, et. al. 

The genomic landscape of Acute Respiratory Distress Syndrome: a meta-analysis by information content of genome-wide studies of the host response.

**medRxiv**, 13.234301089.

[<i class="bi bi-filetype-pdf"></i>](pdf/2024.02.13.24301089v1.full.pdf)

<br/>

#### **2023**

------------------------------------------------------------------------

Swets MC, Kerr S, Scott-Brown J, ..., **Millar JE**, ..., Baillie JK.

Evaluation of pragmatic oxygenation measurement as a proxy for Covid-19 severity.

**Nat. Comms.**, 14:7374.

<https://doi.org/10.1038/s41467-023-42205-6>

[<i class="bi bi-filetype-pdf"></i>](pdf/s41467-023-42205-6.pdf)

<br />

Malfertheiner MV, Garrett A, Passmore M, ..., **Millar JE**, ..., Fraser JF.

The effects of nitric oxide on coagulation and inflammation in ex-vivo models of extracorporeal membrane oxygenation and cardiopulmonary bypass.

**Artif. Organs**, 47(10):1581-1591.

<https://doi.org/10.1111/aor.14608>

[<i class="bi bi-filetype-pdf"></i>](pdf/Malfertheiner_NO_ArtifOrgans.pdf)

<br />

Pairo-Castineira E, Rawlik K, Bretherick AD, ..., **Millar JE**, ..., Baillie JK.

GWAS and meta-analyses identifies 49 genetic variants underlying critical COVID-19.

**Nature**, 617(7962):764-768.

<https://doi.org/10.1038/s41586-023-06034-3>

[<i class="bi bi-filetype-pdf"></i>](pdf/s41586-023-06034-3.pdf)

<br />

See Hoe LE, Li Bassi G, Wildi K, ..., **Millar JE**, ..., Fraser JF.

Donor heart ischemic time can be extended to 8 hours using hypothermic machine perfusion in sheep.

**J. Heart Lung Transplant.**, S1053-2498(23)01819-3.

<https://doi.org/10.1016/j.healun.2023.03.020>

[<i class="bi bi-filetype-pdf"></i>](pdf/PIIS1053249823018193.pdf)

<br />

#### **2022**

------------------------------------------------------------------------

**Millar JE**, Boyle AJ, Drake TD, et. al.

Extracorporeal carbon dioxide removal in acute hypoxaemic respiratory failure: a systematic review, Bayesian meta-analysis, and trial sequential analysis.

**Eur. Respir. Rev.**, 31:220030.

<https://doi.org/10.1183/16000617.0030-2022>

[<i class="bi bi-filetype-pdf"></i>](pdf/220030.pdf)

<br />

Wildi K, Hyslop K, **Millar JE**, et. al.

Validation of mRNA markers expressed in human ARDS subgroups in an ovine model of ARDS phenotypes.

**Front. Med.**, 9:961336.

<https://doi.org/10.3389/fmed.2022.961336>

[<i class="bi bi-filetype-pdf"></i>](pdf/fmed-09-961336.pdf)

<br />

**Millar JE**, Neyton L, Seth S, et. al.

Distinct clinical symptom patterns in patients hospitalised with COVID-19 in an analysis of 59,011 patients in the ISARIC-4C study.

**Sci. Rep.**, 12, 6843.

[https://doi.org/10.1038/s41598-022-08032-30](https://doi.org/10.1038/s41598-022-08032-3)

[<i class="bi bi-filetype-pdf"></i>](pdf/s41598-022-08032-3.pdf)

<br />

Kousathanas A, Pairo-Castineira E, Rawlik K, ..., **Millar JE**, ..., Baillie JK.

Whole genome sequencing reveals host factors underlying critical COVID-19.

**Nature**, 607(7917):97-103.

<https://doi.org/10.1038/s41586-022-04576-6>

[<i class="bi bi-filetype-pdf"></i>](pdf/s41586-022-04576-6.pdf)

<br />

Reyes LF, Murthy S, Garcia-Gallo E, ..., **Millar JE**, ..., Olliaro PL.

Clinical characteristics, risk factors and outcomes in patients with severe COVID-19 registered in the ISARIC WHO clinical characterisation protocol: a prospective, multinational, multicentre, observational study.

**Eur. Respir. J. Open Res.**, 8(1):00552-2021.

<https://doi.org/10.1183/23120541.00552-2021>

[<i class="bi bi-filetype-pdf"></i>](pdf/00552-2021.full.pdf)

<br />

Winslow RL, Zhou J, Windle EF, ..., **Millar JE**, ...Green CA.

SARS-CoV-2 environmental contamination from hospitalised patients with COVID-19 receiving aerosol-generating procedures.

**Thorax**, 77(3):259-267.

<https://doi.org/10.1136/thoraxjnl-2021-218035>

[<i class="bi bi-filetype-pdf"></i>](pdf/259.pdf)

<br />

#### **2021**

------------------------------------------------------------------------

Li Bassi G, Suen JY, Dalton HJ, ..., **Millar JE**, ..., Fraser JF.

An appraisal of respiratory system compliance in mechanically ventilated COVID-19 patients.

**Crit. Care**, 25: 199.

<https://doi.org/10.1186/s13054-021-03518-4>

[<i class="bi bi-filetype-pdf"></i>](pdf/s13054-021-03518-4.pdf)

<br />

McNamee JJ, Gillies MA, Barrett NA, ..., **Millar JE**, ..., McAuley DF.

Effect of lower tidal volume ventilation facilitated by extracorporeal carbon dioxide removal vs standard care ventilation on 90-day mortality in patients with acute hypoxemic respiratory failure: the REST randomized trial.

**JAMA**, 326(11):1013-1023.

<https://doi.org/10.1001/jama.2021.13374>

<br />

Dolby HW, Potey P, Wilder-Smith AB, ..., **Millar JE**, ..., Russell CD.

Histological evidence of pulmonary microthrombosis and vasculitis in life-threatening respiratory virus disease.

**Open Forum Inf. Dis.**, 8(2):ofaa640.

<https://doi.org/10.1093/ofid/ofaa640>

[<i class="bi bi-filetype-pdf"></i>](pdf/ofaa640.pdf)

<br />

Ki KK, **Millar JE**, Langguth D, et. al.

Current understanding of leukocyte phenotypic and functional modulation during extracorporeal membrane oxygenation: a narrative review.

**Front. Immunol.**, 11:600684.

<https://doi.org/10.3389/fimmu.2020.600684>

[<i class="bi bi-filetype-pdf"></i>](pdf/fimmu-11-600684.pdf)

<br />

Fulton R, **Millar JE**, Merza M, et. al.

Prophylactic postoperative high flow nasal oxygen versus conventional therapy in obese patients undergoing bariatric surgery (OXYBAR): a pilot randomised controlled trial.

**Obes. Surg.**, 31(11):47994807.

<https://doi.org/10.1007/s11695-021-05644-y>

<br />

**Millar JE**, Wildi K,Bartnikowski N,et. al.

Characterizing preclinical sub-phenotypic models of acute respiratory distress syndrome: an experimental ovine study.

**Physiol. Rep.**, 9(19):e15048.

<https://doi.org/10.14814/phy2.15048>

[<i class="bi bi-filetype-pdf"></i>](pdf/Characterizingpreclinical.pdf)

<br />

See Hoe LE, Wildi K, Obonyo NG, ..., **Millar JE**, ..., Fraser JF.

A clinically relevant sheep model of orthotopic heart transplantation 24 h after donor brainstem death.

**Intensive Care Med. Exp.**, 9(1):60.

<https://doi.org/10.1186/s40635-021-00425-4>

[<i class="bi bi-filetype-pdf"></i>](pdf/s40635-021-00425-4.pdf)

<br />

Pairo-Castineira E, Clohisey S, Klaric L, ..., **Millar JE**, ..., Baillie JK.

Genetic mechanisms of critical illness in COVID-19.

**Nature**, 591(7848):92-98.

<https://doi.org/10.1038/s41586-020-03065-y>

[<i class="bi bi-filetype-pdf"></i>](pdf/s41586-020-03065-y.pdf)

<br />

COVID-19 Host Genetics Initiative.

Mapping the human genetic architecture of COVID-19.

**Nature**, 600(7889):472-477.

<https://doi.org/10.1038/s41586-021-03767-x>

[<i class="bi bi-filetype-pdf"></i>](pdf/s41586-021-03767-x.pdf)

<br />

#### **2020**

------------------------------------------------------------------------

Parkinson N, Rodgers N, Fourman MH, ..., **Millar JE**, ..., Clohisey S.

Dynamic data-driven meta-analysis for prioritisation of host genes implicated in COVID-19.

**Sci. Rep.**, 10(1):22303.

<https://doi.org/10.1038/s41598-020-79033-3>

[<i class="bi bi-filetype-pdf"></i>](pdf/s41598-020-79033-3.pdf)

<br />

Soulsby CR, Hutchison, Gardner J, ..., **Millar JE**.

Socio-economic deprivation and the risk of death after ICU admission with COVID-19: The poor relation.

**J. Intensive Care Soc.**,

<https://doi.org/10.1177/1751143720978855>

[<i class="bi bi-filetype-pdf"></i>](pdf/poorrelation.pdf)

<br />

Gorman E, **Millar JE**, McAuley D, et. al.

Mesenchymal stromal cells for acute respiratory distress syndrome (ARDS), sepsis, and COVID-19 infection: optimizing the therapeutic potential.

**Expert Rev. Respir. Med.**, 15(3):301-324.

<https://doi.org/10.1080/17476348.2021.1848555>

<br />

Burton F, Lowe DJ, **Millar JE**, et. al.

Propofol target-controlled infusion in emergency department sedation (Peo-TEDS): a multicentre, single-arm feasibility study.

**Emerg. Med. J.**, 38(3):205--210.

<https://doi.org/10.1136/emermed-2020-209686>

[<i class="bi bi-filetype-pdf"></i>](pdf/205.pdf)

<br />

Li Bassi G, Suen JY, Barnett AG, ..., **Millar J**, ..., Fraser JF.

Design and rationale of the COVID-19 Critical Care Consortium international, multicentre, observational study.

**BMJ Open**, 10(12):e041417.

<https://doi.org/10.1136/bmjopen-2020-041417>

[<i class="bi bi-filetype-pdf"></i>](pdf/e041417.pdf)

<br />

Heinser S, Rozencwajg S, Suen JY, ..., **Millar JE**.

Heart failure supported by veno-arterial extracorporeal membrane oxygenation (ECMO): a systematic review of pre-clinical models.

**Intensive Care Med. Exp.**, 8:16.

<https://doi.org/10.1186/s40635-020-00303-5>

[<i class="bi bi-filetype-pdf"></i>](pdf/s40635-020-00303-5.pdf)

<br />

Malfertheiner MV, Koch C, Fisser C, **Millar JE**, et. al.

Incidence of early intra-cranial bleeding and ischaemia in adult veno-arterial extracorporeal membrane oxygenation and extracorporeal cardiopulmonary resuscitation patients: a retrospective analysis of risk factors.

**Perfusion**, 35(1_suppl):8-17.

<https://doi.org/10.1177/0267659120907438>

[<i class="bi bi-filetype-pdf"></i>](pdf/malfertheiner.pdf)

<br />

Malfertheiner MV, Broman LM, Vercaemst L, ..., **Millar JE**, ..., Fraser JF.

Ex vivo models for research in extracorporeal membrane oxygenation: a systematic review of the literature.

**Perfusion**, 35(1_suppl):38-49.

<https://doi.org/10.1177/0267659120907439>

[<i class="bi bi-filetype-pdf"></i>](pdf/malfertheiner2.pdf)

<br />

**Millar JE**, Bartnikowski N, Passmore MR, et. al.

Combined mesenchymal stromal cell therapy and ECMO in ARDS: a randomised controlled trial in sheep. **Am. J. Respir. Crit. Care Med.**, 202(3):383-392.

<https://doi.org/10.1164/rccm.201911-2143OC>

[<i class="bi bi-filetype-pdf"></i>](pdf/201911-2143oc.pdf)

<br />

See Hoe LE, Wells MA, Bartnikowski N, ..., **Millar JE**, ..., Fraser JF.

Heart Transplantation From Brain Dead Donors: A Systematic Review of Animal Models.

**Transplantation**, 104(11):2272-2289.

<https://doi.org/10.1097/TP.0000000000003217>

[<i class="bi bi-filetype-pdf"></i>](pdf/16.pdf)

<br />

Burton FM, Lowe DJ, **Millar JE**, et. al.

Effect of target-controlled propofol infusion to reduce the incidence of adverse events for procedural sedation in the emergency department: a systematic review.

**Eur. J. Emerg. Med.**, 27(4):253259.

<https://doi.org/10.1097/MEJ.0000000000000655>

<br />

#### **2019**

------------------------------------------------------------------------

Ki KK, Passmore MR, Chan CHH, ..., **Millar JE**, ..., Suen JY.

Low flow rate alters haemostatic parameters in an ex-vivo extracorporeal membrane oxygenation circuit.

**Intensive Care Med. Exp.**, 7:51.

<https://doi.org/10.1186/s40635-019-0264-z>

[<i class="bi bi-filetype-pdf"></i>](pdf/s40635-019-0264-z.pdf)

<br />

**Millar JE**, Bartnikowski N, von Bahr V, et. al.

Extracorporeal membrane oxygenation (ECMO) and the acute respiratory distress syndrome (ARDS): a systematic review of pre-clinical models.

**Intensive Care Med. Exp.**, 7(1):18.

<https://doi.org/10.1186/s40635-019-0232-7>

[<i class="bi bi-filetype-pdf"></i>](pdf/s40635-019-0232-7.pdf)

<br />

von Bahr, **Millar JE**, Malfertheiner MV, et. al.

Mesenchymal stem cells may ameliorate inflammation in an ex-vivo model of extracorporeal membrane oxygenation.

**Perfusion**, 34(1suppl):15-21.

<https://doi.org/10.1177/0267659119830857>

<br />

von Bahr V, Kalzen H, Frenckner B, ..., **Millar JE**, ..., Holzgraefe B.

Long-term pulmonary function and quality of life in adults after extracorporeal membrane oxygenation for respiratory failure.

**Perfusion**, 34(1suppl):49-57.

<https://doi.org/10.1177/0267659119830244>

<br />

Obonyo NG, Byrne L, Tung JP, ..., **Millar JE**, ..., Fraser JF.

Pre-clinical study protocol: Blood transfusion in endotoxaemic shock.

**Methods X**, 6:1124--1132.

<https://doi.org/10.1016/j.mex.2019.05.005>

[<i class="bi bi-filetype-pdf"></i>](pdf/PIIS2215016119301244.pdf)

<br />

Burton FM, Lowe DJ, **Millar J**, et. al.

A study protocol for a feasibility study: Propofol Target-Controlled Infusion in Emergency Department Sedation (PRoTEDS) -- a multicentre feasibility study protocol.

**Pilot Feasibility Stud.**, 5:27.

<https://doi.org/10.1186/s40814-019-0412-y>

[<i class="bi bi-filetype-pdf"></i>](pdf/s40814-019-0412-y.pdf)

<br />

Fanning JP, SeeHoe LE, Passmore MR, ..., **Millar JE**, ..., Fraser JF.

Neuron-Specific Enolase and matrix metalloproteinase 9 signal perioperative silent brain infarction during or after transcatheter aortic valve implantation.

**Am. J. Cardiol.**, 123(3):434-439.

<https://doi.org/10.1016/j.amjcard.2018.10.022>

<br />

**Millar JE**, von Bahr V, Malfertheiner MV, et. al.

Administration of mesenchymal stem cells during ECMO results in a rapid decline in oxygenator performance.

**Thorax**, 74(2):194-196.

<http://dx.doi.org/10.1136/thoraxjnl-2017-211439>

[<i class="bi bi-filetype-pdf"></i>](pdf/194.pdf)

<br />

#### **2018**

------------------------------------------------------------------------

Fulton R, **Millar JE**, Merza M, et. al.

High flow nasal oxygen after bariatric (OXYBAR), prophylactic post-operative high flow nasal oxygen versus conventional oxygen therapy in obese patients undergoing bariatric surgery: a study protocol for a randomised controlled pilot trial.

**Trials**, 19(1):402.

<http://dx.doi.org/10.1007/s11695-021-05644-y>

<br />

Fanning JP, See Hoe LE, Passmore MR, ..., **Millar JE**, ..., Fraser JF.

Differential immunological profiles herald magnetic resonance imaging-defined perioperative cerebral infarction.

**Ther. Adv. Neurol. Dis.**, 11:1756286418759493.

<http://dx.doi.org/10.1177/1756286418759493>

[<i class="bi bi-filetype-pdf"></i>](pdf/fanning.pdf)

<br />

#### **2017**

------------------------------------------------------------------------

Malfertheiner MV, Pimenta LP, von Bahr V, **Millar JE**, et. al.

Acquired von Willebrand syndrome in respiratory extracorporeal life support: a systematic review of the literature.

**Crit. Care Resusc.**, 19(Suppl 1):45-52.

<https://pubmed.ncbi.nlm.nih.gov/29084501/>

<br />

#### **2016**

------------------------------------------------------------------------

**Millar JE**, Fanning JP, McDonald CI, et. al.

The inflammatory response to extracorporeal membrane oxygenation (ECMO): a review of the pathophysiology.

**Crit. Care**, 20:387.

<https://doi.org/10.1186/s13054-016-1570-4>

[<i class="bi bi-filetype-pdf"></i>](pdf/s13054-016-1570-4.pdf)

<br />

Devaney J, Smyth R, Lutton S, ..., **Millar JE**.

The soda dipstick: A convenient and cost-effective means of identifying the sugar content of soft drinks.

**J. Diabetes**, 8(6):877-878.

<https://doi.org/10.1111/1753-0407.12431>

<br />

Lowe DJ, **Millar JE**, Dignon N, Ireland A.

Top 10 lessons from the Glasgow major incidents.

**Emerg. Med. J.**, 33(8):596-7.

<https://doi.org/10.1136/emermed-2015-205626>

<br />

#### **2014**

------------------------------------------------------------------------

Fitzgerald M, **Millar J**, Blackwood B, et. al.

Extracorporeal carbon dioxide removal for patients with acute respiratory failure secondary to the Acute Respiratory Distress Syndrome: a systematic review.

**Crit. Care**, 18(3):222.

<https://doi.org/10.1186/cc13875>

[<i class="bi bi-filetype-pdf"></i>](pdf/cc13875.pdf)

<br />

**Millar J**, Lutton S, O'Connor P.

The use of high flow nasal oxygen in the management of hypercarbic respiratory failure.

**Ther. Adv. Respir. Dis.**, 8(2):63-4.

<https://doi.org/10.1177/1753465814521890>

[<i class="bi bi-filetype-pdf"></i>](pdf/millar2014.pdf)

<br />

### Editorials

------------------------------------------------------------------------

<br />

#### **2024**

------------------------------------------------------------------------

**Millar JE**, Docherty AB.

It ain’t what you do (it’s the way that you do it): modulating the host response in sepsis. 

**Anaesthesia**, Online ahead of print.

<https://doi.org/10.1111/anae.16263>

[<i class="bi bi-filetype-pdf"></i>](pdf/Anaesthesia.pdf)

<br/>

#### **2023**

------------------------------------------------------------------------

**Millar JE**, O'Kane CM.

Mesenchymal stromal cells and ARDS: more questions than answers.

**Am. J. Respir. Crit. Care Med.**, 208(12):1257-1259.

<https://doi.org/10.1164/rccm.202310-1847ED>

[<i class="bi bi-filetype-pdf"></i>](pdf/Millar_MSCsMoreQuestions-AJRCCM_2023.pdf)

<br />

**Millar JE**, McAuley DF, Marini JJ.

Driving pressure - what's the harm?

**Crit. Care Med.**, 51(7): 967-970.

<https://doi.org/10.1097/CCM.0000000000005874>

[<i class="bi bi-filetype-pdf"></i>](pdf/Driving_Pressure.pdf)

<br />

#### **2020**

------------------------------------------------------------------------

Russell CD, **Millar JE**, Baillie JK.

Clinical Evidence Does Not Support Corticosteroid Treatment for 2019-nCoV Lung Injury.

**Lancet**, 395(10223): 473--475.

<https://doi.org/10.1016/S0140-6736(20)30317-2>

[<i class="bi bi-filetype-pdf"></i>](pdf/PIIS0140673620303172.pdf)

<br />

**Millar JE**, Busse R, Fraser JF, et. al.

Apples and oranges: international comparisons of COVID-19 observational studies in ICUs.

**Lancet Respir. Med.**, 8(10):952--953.

<https://doi.org/10.1016/S2213-2600(20)30368-4>

[<i class="bi bi-filetype-pdf"></i>](pdf/PIIS2213260020303684.pdf)

<br />

#### **2015**

------------------------------------------------------------------------

**Millar JE**, Fraser JF, McAuley DF.

Mesenchymal stromal cells and the acute respiratory distress syndrome (ARDS): challenges for clinical application.

**Thorax**, 70(7):611-2.

<http://dx.doi.org/10.1136/thoraxjnl-2015-207121>

[<i class="bi bi-filetype-pdf"></i>](pdf/611.pdf)

<br />

### Letters

------------------------------------------------------------------------

<br />

#### **2016**

------------------------------------------------------------------------

**Millar JE**, Lutton S, McLaughlin R.

Need for a systematic audit of trauma care in Northern Ireland.

**BMJ**, 353:i2025.

<http://dx.doi.org/10.1136/bmj.i2025>

<br />

### Book chapters

------------------------------------------------------------------------

<br />

#### **2022**

------------------------------------------------------------------------

Hartley EL, **Millar JE**, Fraser JF.

The unholy blood: biomaterial interaction in extracorporeal circulation. Extracorporeal Membrane Oxygenation: An interdisciplinary problem-based learning approach.

Oxford University Press.

<https://doi.org/10.1093/med/9780197521304.003.0012>

<br />

#### **2017**

------------------------------------------------------------------------

**Millar JE**, Gregory S, Stevens M, Fraser JF, Bartlett B.

Past, Present, and Future. Mechanical Circulatory and Respiratory Support.

Academic Press (Elsevier).

<https://doi.org/10.1016/B978-0-12-810491-0.00025-4>
